# Site settings
title: Basic blog site
email: pabdavis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a basic blog site using jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pabdavis.github.io" # the base hostname & protocol for your site
twitter_username: pabdavis
github_username:  pabdavis

# Build settings
markdown: kramdown
